name: Build Test

on:
  push:
    branches:
      - dev-tabs
    tags-ignore:
      - v*
      -
  pull_request:
    branches:
      - master
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
      - run: flutter pub get
      - name: Analyze files
        run: flutter analyze .


  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.x'
          channel: 'stable'
      - run: flutter pub get
      - name: Build Android app bundle
        run: flutter build appbundle --release
